#!/bin/bash

#the first argument should be the repository name
#the second argument should be the GitHub user name
curl -u "$2" https://api.github.com/user/repos -d '{"name":"'$1'"}'
mkdir $1
cd $1
echo "# $1" >> README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin https://github.com/$2/$1.git
git push -u origin master
